### ISSUE TITLE
Align semantics of `InsertField` and `insertRField'`

### ISSUE THREAD

**Issue by meditans** [Lysxia/generic-data-surgery#6]
In the `Internal` module of `generic-data-surgery` we have some type families that we use to calculate the generic synthetic types. I would propose to make their semantics closer to the semantics of the term-level functions, and to export them, so that:
```
fromOR' $ insertRField' @"pk" @0 @Int 0 $ toOR p
```
would produce something of type:
```
Data (Eval (InsertField 0 ('Just "pk") Int (GHC.Rep Person))) ()
```
instead of the current
```
Data (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep Person))))) ()
```

(see https://gist.github.com/meditans/d3b5970d7d1d7cb0f4af98091a41f2c1 for the question that prompted this request)

**Comment by Lysxia** [comment]
Maybe  we can wrap the application of these two families together with `Eval` in a new type synonym. It seems difficulr to get rid of them entirely.

**Comment by meditans** [comment]
That would be a good thing, yes. Another thing to think about would be how a signature like this one could be simplified:

``` haskell
newtype WithId a =
  WithId (Data (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))) ())

instance
  ( Functor (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a)))))
  , Contravariant (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a)))))
  ) => Generic (WithId a) where
  type Rep (WithId a) = Rep (Data (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))) ())
  from (WithId a) = GHC.Generics.from a
  to a = WithId (to a)

addKey'
  :: ( Linearize (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))) ~ Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a)))
     , Eval (FieldIndex "pk" (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))) ~ 0
     , Eval (FieldTypeAt 0 (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))) ~ RowID
     , Eval (RemoveField 0 (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))) ~ Linearize (Rep a)
     , Arborify (Linearize (Rep a)) ~ Rep a
     , GArborify (Arborify (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a)))))
     , GInsertField 0 (Eval (InsertField 0 ('Just "pk") RowID (Linearize (Rep a))))
     , Generic a
     , GLinearize (Rep a)
     )
  => a -> WithId a
addKey' a = WithId $ fromOR' $ insertRField' @"pk" @0 @RowID def $ toOR a
```
notice I had to create the `Generic` instance manually because I needed the two constraints. For the ergonomy of the `addKey'` type signature, I think that most of those constraints are trying to imply that my data is a record. Maybe that could have a type synonym for itself.

**Comment by meditans** [comment]
Also, a high level description of what `Arborify` and `Linearize` are trying to accomplish would be great (looking at the type families definition only gets me so far)

**Comment by Lysxia** [comment]
In draft PR #9 I've created a new interface to make surgeries first-class at the type level. There are operators to compose and apply surgeries, so that with sufficient documentation (TODO) you wouldn't need to know anything about `Arborify`/`Linearize` or *first-class-families*.

That snippet cleans up to (see `test/synthetic.hs`):

```haskell
type InsertId = (InsertField 0 ('Just "pk") RowId :: MajorSurgery k)

newtype WithId a =
  WithId (Data (Operate (Rep a) InsertId) ())

deriving newtype instance
  ( Generic a
  , Functor (Operate (Rep a) InsertId)
  , Contravariant (Operate (Rep a) InsertId)
  ) => Generic (WithId a)

addKey ::
  ( Generic a
  , Perform (Rep a) InsertId
  ) => RowId -> a -> WithId a
addKey i = WithId . fromOR' . insertRField' @"pk" @0 @RowId i . toOR
```
